#ifndef GAMETRAINER_LUA_STATUS_HPP
#define GAMETRAINER_LUA_STATUS_HPP

enum LUA_STATUS {
    LUA_STATUS_HAS_VALUE,
    LUA_STATUS_HAS_NO_VALUE,
    LUA_STATUS_HAS_ANOTHER_TYPE
};

#endif //GAMETRAINER_LUA_STATUS_HPP
