dist: trusty
sudo: true
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-6
            - clang-5.0

before_install:
    - cd temp
    - git clone https://github.com/google/googletest.git gtest
#    - pyenv global 3.6.3
#    - pip3 install --user cpp-coveralls pyyaml
    - cd ..
    - sudo apt-get update -y
    - sudo apt-get install cmake -y
    - sudo apt-get upgrade -y --allow-unauthenticated
    - cmake --version
    - make A=x64

#script:
#    - cd temp
#    - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
#    - cmake --build .
#    - ./tests
#    - cd ..
#
#after_success:
#    - cd temp
#    - cp ./.ci/.coveralls.yml ./
#    - coveralls --skip-ssl-verify --root . -E ".*CMakeFiles.*"
#    - cd ..
