dist: trusty
sudo: true
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-6
            - clang-5.0

before_install:
    - cd temp
    - git clone https://github.com/google/googletest.git gtest
    - git clone https://github.com/eddyxu/cpp-coveralls.git
    - cd cpp-coveralls
    - sudo apt-get update
    - sudo apt-get install python3-pip
    - pip3 install --user -r requirements.txt
    - pip3 install --user pyyaml
    - cd ../..

script:
    - cd temp
    - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
    - cmake --build .
    - ./tests
    - cd ..

after_success:
    - cd temp
    - python3 coveralls.py --skip-ssl-verify --root . -E ".*CMakeFiles.*"
    - cd ..
