dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-6
            - clang-5.0

before_install:
    - cd temp
    - git clone https://github.com/google/googletest.git gtest
#    - pyenv global 3.6.3
#    - pip3 install --user cpp-coveralls pyyaml
    - cd ..
    # Download and install recent cmake
    - |
        if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
          CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
          mkdir -p cmake
          travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=cmake/bin:${PATH}
        fi
    - make A=x64

#script:
#    - cd temp
#    - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
#    - cmake --build .
#    - ./tests
#    - cd ..
#
#after_success:
#    - cd temp
#    - cp ./.ci/.coveralls.yml ./
#    - coveralls --skip-ssl-verify --root . -E ".*CMakeFiles.*"
#    - cd ..
