image:
    - Visual Studio 2019
    - Visual Studio 2017
    - Visual Studio 2015

#remove it
skip_non_tags: true

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\GameTrainer
shallow_clone: true

matrix:
    fast_finish: false

    exclude:
#        -   image: Visual Studio 2015
#            TOOLCHAIN: msvc15
#
#        -   image: Visual Studio 2019
#            TOOLCHAIN: msvc15

platform:
    - x64
    - x86

configuration:
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15
        - TOOLCHAIN: msvc16

install:
    - appveyor UpdateBuild -Version %APPVEYOR_REPO_TAG_NAME%
    - call .ci/install.bat %PLATFORM% %TOOLCHAIN% %APPVEYOR_REPO_TAG_NAME%

build_script:
    - cmake %CMAKE_CONFIGURE_FLAGS%
    - cmake %CMAKE_BUILD_FLAGS%
    - call .ci/zip.bat

artifacts:
    - path: bin/**/.zip
      name: app

deploy:
    tag: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub

    auth_token:
        secure: JBkOxrXSpCaqb+CJ2KADRvCOfQyjMXhSA92UIaoxBNWhLnsY3Mp1SOlke3r5P/Rs

    artifact: app
    force_update: true

    on:
        appveyor_repo_tag: true

    description: "
# GameTrainer

## Support Games:

- Dead Island

- Dead Island: Riptide

- Killing Floor

- Killing Floor2

- Left 4 Dead2


"
