image:
    - Visual Studio 2019
    - Visual Studio 2017

skip_non_tags: true

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\GameTrainer
shallow_clone: true

matrix:
    fast_finish: false

    exclude:
        -   image: Visual Studio 2019
            TOOLCHAIN: msvc15

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc16

platform:
    - x64
    - x86

configuration:
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc15
        - TOOLCHAIN: msvc16

install:
    - appveyor UpdateBuild -Version %APPVEYOR_REPO_TAG_NAME%
    - call .ci/install-testing-deps.bat
    - call .ci/set-env.bat %PLATFORM% %TOOLCHAIN% %APPVEYOR_REPO_TAG_NAME%

build_script:
    - cmake %CMAKE_CONFIGURE_FLAGS%
    - cmake %CMAKE_BUILD_FLAGS%

after_build:
    - call .ci/zip.bat

test_script:
    - cd build
    - ctest -VV -C Release
    - cd ..

artifacts:
    - path: bin/**/.zip
      name: app

deploy:
    tag: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub

    auth_token:
        secure: JBkOxrXSpCaqb+CJ2KADRvCOfQyjMXhSA92UIaoxBNWhLnsY3Mp1SOlke3r5P/Rs

    artifact: app
    force_update: true

    on:
        appveyor_repo_tag: true

    description: "
# GameTrainer

Powered by C++17 & Lua-5.3.4

## Support Games:

- Dead Island

- Dead Island: Riptide

- Killing Floor

- Killing Floor 2

- Left 4 Dead 2

## System Requirements

- Windows 10

- Microsoft Visual C++ Redistributable ([x86](https://aka.ms/vs/16/release/VC_redist.x86.exe) / [x64](https://aka.ms/vs/16/release/VC_redist.x64.exe))



"
