image:
    #- Visual Studio 2015
    - Visual Studio 2017
    #- Visual Studio 2019

#remove it
skip_non_tags: true

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\GameTrainer
shallow_clone: true

matrix:
    fast_finish: false

    exclude:
        -   image: Visual Studio 2015
            TOOLCHAIN: msvc15

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc10

        -   image: Visual Studio 2019
            TOOLCHAIN: msvc10

        -   image: Visual Studio 2019
            TOOLCHAIN: msvc12

        -   image: Visual Studio 2019
            TOOLCHAIN: msvc15

platform:
    - x64
    #- x86

configuration:
    - Release

environment:
    matrix:
        #- TOOLCHAIN: msvc10
        #- TOOLCHAIN: msvc12
        #- TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15
        #- TOOLCHAIN: msvc16

install:
    - call .ci/install.bat %TOOLCHAIN% %PLATFORM% %APPVEYOR_REPO_TAG_NAME%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%
    #- 7z -o x64.zip x64.exe data_with_lua
    #- 7z -o x86.zip x86.exe data_with_lua

artifacts:
    - path: bin/*.exe
      name: app

deploy:
    description: 'This is description\r\n<br> from appveyor'
    tag: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub

    auth_token:
        secure: JBkOxrXSpCaqb+CJ2KADRvCOfQyjMXhSA92UIaoxBNWhLnsY3Mp1SOlke3r5P/Rs

    artifact: app
    force_update: true

    on:
        appveyor_repo_tag: true
